### 2-1. 모든 유저 조회

    GET {{baseUrl}}/entity/users

### 2-2. 특정 유저 조회

    GET {{baseUrl}}/entity/users/1

### 2-3. 없는 유저 조회

    GET {{baseUrl}}/entity/users/6

### 2-4. 유저 등록
    POST {{baseUrl}}/entity/users/
Content-Type: application/json ### 요청 시 전달하는 데이터의 타입 명시

{
"id": "user04",
"pwd": "pass04",
"name": "강감찬"
}


### 2-4. 유저 등록
PUT {{baseUrl}}/entity/users/3
Content-Type: application/json ### 요청 시 전달하는 데이터의 타입 명시

{
  "id": "user04",
  "pwd": "pass04",
  "name": "강감찬"
}

### 2-5. 유저 등록
DELETE {{baseUrl}}/entity/users/3